import { Category, Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.ZH_TW]: {
    title: 'A.C.M. JUNKSHOP',
    home: {
      record: '記帳',
      view: '查看',
      settings: '設定',
    },
    auth: {
      loginTitle: '歡迎回來',
      loginSubtitle: '請登入以繼續管理您的帳務',
      loginButton: '使用 Google 帳號登入',
      loggingIn: '登入中...',
      welcome: '歡迎，',
      logout: '登出',
      loginError: '登入失敗，請重試',
    },
    record: {
      title: '新增紀錄',
      companyName: 'A.C.M. JUNKSHOP',
      date: '日期',
      colIndex: '序號',
      colMaterial: '材料名稱',
      colWeight: '重量',
      colDeduction: '%',
      colPrice: '售價/KG',
      colResult: '結果',
      grandTotal: '總計',
      addRow: '增加欄位',
      save: '儲存',
      saved: '已儲存！',
      invoice: '發票',
      enterCode: '請輸入驗證碼以儲存：',
      invalidCode: '驗證碼錯誤',
      uploadSuccess: '上傳成功',
      clear: 'Delete',
    },
    invoice: {
      proofCopy: '收據',
      yearMonth: '113年 01-02月',
      invoiceNum: 'AB-12345678',
      randomNum: '隨機碼',
      seller: '賣方',
      item: '項目',
      qty: '重量',
      price: '單價',
      amt: '金額',
      totalAmount: '總金額',
      cash: '現金',
      print: '列印',
      close: '關閉',
      signature: '簽名欄',
      footerNote: '此為虛擬發票,無法律依據',
    },
    view: {
      title: '紀錄列表',
      filterDateStart: '開始日期',
      filterDateEnd: '結束日期',
      filterMaterial: '搜尋材料...',
      exportCSV: '匯出 Excel',
      printPDF: '列印 PDF',
      colIndex: '序號',
      colDate: '日期',
      colMaterial: '材料名稱',
      colWeight: '重量',
      colDeduction: '%',
      colPrice: '售價/KG',
      colResult: '結果',
      noRecords: '無符合資料',
      delete: '刪除',
      totalSummary: '篩選總計',
    },
    settings: {
      title: '設定',
      language: '語言',
      selectLanguage: '選擇系統語言',
    },
    categories: {
      [Category.FOOD]: '飲食',
      [Category.TRANSPORT]: '交通',
      [Category.SHOPPING]: '購物',
      [Category.ENTERTAINMENT]: '娛樂',
      [Category.HOUSING]: '居家',
      [Category.OTHER]: '其他',
    },
  },
  [Language.EN]: {
    title: 'A.C.M. JUNKSHOP',
    home: {
      record: 'Record',
      view: 'View',
      settings: 'Settings',
    },
    auth: {
      loginTitle: 'Welcome Back',
      loginSubtitle: 'Sign in to manage your records',
      loginButton: 'Sign in with Google',
      loggingIn: 'Signing in...',
      welcome: 'Welcome, ',
      logout: 'Logout',
      loginError: 'Login failed, please try again',
    },
    record: {
      title: 'Add Record',
      companyName: 'A.C.M. JUNKSHOP',
      date: 'Date',
      colIndex: '#',
      colMaterial: 'Material',
      colWeight: 'Kilo',
      colDeduction: '%',
      colPrice: 'Price/KG',
      colResult: 'Result',
      grandTotal: 'Total',
      addRow: 'Add Row',
      save: 'Save',
      saved: 'Saved!',
      invoice: 'Invoice',
      enterCode: 'Enter verification code to save:',
      invalidCode: 'Invalid verification code',
      uploadSuccess: 'Upload successful',
      clear: 'Delete',
    },
    invoice: {
      proofCopy: 'Receipt',
      yearMonth: '2024-01',
      invoiceNum: 'AB-12345678',
      randomNum: 'Random',
      seller: 'Seller',
      item: 'Items',
      qty: 'Kilo',
      price: 'Price',
      amt: 'Amount',
      totalAmount: 'Total Amount',
      cash: 'Cash',
      print: 'Print',
      close: 'Close',
      signature: 'Signature',
      footerNote: 'Virtual invoice, no legal basis',
    },
    view: {
      title: 'Records List',
      filterDateStart: 'Start Date',
      filterDateEnd: 'End Date',
      filterMaterial: 'Search Material...',
      exportCSV: 'Export Excel',
      printPDF: 'Print PDF',
      colIndex: '#',
      colDate: 'Date',
      colMaterial: 'Material',
      colWeight: 'Kilo',
      colDeduction: '%',
      colPrice: 'Price/KG',
      colResult: 'Result',
      noRecords: 'No records found',
      delete: 'Delete',
      totalSummary: 'Filtered Total',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      selectLanguage: 'Select Language',
    },
    categories: {
      [Category.FOOD]: 'Food',
      [Category.TRANSPORT]: 'Transport',
      [Category.SHOPPING]: 'Shopping',
      [Category.ENTERTAINMENT]: 'Entertainment',
      [Category.HOUSING]: 'Housing',
      [Category.OTHER]: 'Other',
    },
  },
  [Language.FIL]: {
    title: 'A.C.M. JUNKSHOP',
    home: {
      record: 'Maglista',
      view: 'Tingnan',
      settings: 'Setting',
    },
    auth: {
      loginTitle: 'Maligayang Pagbabalik',
      loginSubtitle: 'Mag-sign in para pamahalaan ang mga record',
      loginButton: 'Mag-sign in gamit ang Google',
      loggingIn: 'Nagsa-sign in...',
      welcome: 'Mabuhay, ',
      logout: 'Mag-logout',
      loginError: 'Nabigo ang pag-login, subukang muli',
    },
    record: {
      title: 'Magdagdag',
      companyName: 'A.C.M. JUNKSHOP',
      date: 'Petsa',
      colIndex: '#',
      colMaterial: 'Materyales',
      colWeight: 'Kilo',
      colDeduction: '%',
      colPrice: 'Presyo/KG',
      colResult: 'Resulta',
      grandTotal: 'Kabuuan',
      addRow: 'Magdagdag ng Hilera',
      save: 'I-save',
      saved: 'Nai-save na!',
      invoice: 'Resibo',
      enterCode: 'Ipasok ang verification code:',
      invalidCode: 'Maling code',
      uploadSuccess: 'Matagumpay na na-upload',
      clear: 'Delete',
    },
    invoice: {
      proofCopy: 'Resibo',
      yearMonth: '2024-01',
      invoiceNum: 'AB-12345678',
      randomNum: 'Random',
      seller: 'Nagbenta',
      item: 'Bagay',
      qty: 'Kilo',
      price: 'Presyo',
      amt: 'Halaga',
      totalAmount: 'Kabuuan',
      cash: 'Cash',
      print: 'I-print',
      close: 'Isara',
      signature: 'Lagda',
      footerNote: 'Virtual na resibo, walang legal na batayan',
    },
    view: {
      title: 'Listahan ng Rekord',
      filterDateStart: 'Simulang Petsa',
      filterDateEnd: 'Huling Petsa',
      filterMaterial: 'Maghanap...',
      exportCSV: 'I-export Excel',
      printPDF: 'I-print PDF',
      colIndex: '#',
      colDate: 'Petsa',
      colMaterial: 'Materyales',
      colWeight: 'Kilo',
      colDeduction: '%',
      colPrice: 'Presyo/KG',
      colResult: 'Resulta',
      noRecords: 'Walang nakitang rekord',
      delete: 'Tanggalin',
      totalSummary: 'Kabuuan',
    },
    settings: {
      title: 'Mga Setting',
      language: 'Wika',
      selectLanguage: 'Pumili ng Wika',
    },
    categories: {
      [Category.FOOD]: 'Pagkain',
      [Category.TRANSPORT]: 'Transportasyon',
      [Category.SHOPPING]: 'Pamimili',
      [Category.ENTERTAINMENT]: 'Libangan',
      [Category.HOUSING]: 'Bahay',
      [Category.OTHER]: 'Iba pa',
    },
  },
};